"""Swarm Goal Planner API — SSE streaming endpoint."""

from __future__ import annotations

import json
from typing import AsyncGenerator

from fastapi import APIRouter, Query
from fastapi.responses import StreamingResponse

from app.services.swarm.coordinator import run_swarm
from app.services.swarm.schemas import GoalInput

router = APIRouter(prefix="/swarm", tags=["Swarm"])


async def _event_stream(goal_input: GoalInput) -> AsyncGenerator[str, None]:
    """Generate SSE-formatted events from the swarm coordinator."""

    async for event in run_swarm(goal_input):
        payload = json.dumps(event.model_dump(), default=str)
        yield f"event: {event.event_type}\ndata: {payload}\n\n"

    # Sentinel event to signal completion
    yield "event: done\ndata: {}\n\n"


@router.get("/plan")
async def stream_swarm_plan(
    goal: str = Query(..., description="Natural language financial goal"),
    initial_capital: float | None = Query(None, description="Starting capital in INR"),
    monthly_income: float | None = Query(None, description="Monthly income in INR"),
    risk_tolerance: str | None = Query(None, description="conservative | moderate | aggressive"),
):
    """
    Stream a financial plan generated by the AI swarm.

    Returns Server-Sent Events (SSE) with agent thoughts and results.
    Connect using EventSource in the browser.
    """
    goal_input = GoalInput(
        goal=goal,
        initial_capital=initial_capital,
        monthly_income=monthly_income,
        risk_tolerance=risk_tolerance,  # type: ignore[arg-type]
    )

    return StreamingResponse(
        _event_stream(goal_input),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable nginx buffering
        },
    )
