"""add_market_data_and_history

Revision ID: d0b74cd6e4ae
Revises: 24a258075be2
Create Date: 2026-02-11 19:10:58.134965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b74cd6e4ae'
down_revision: Union[str, Sequence[str], None] = '24a258075be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_index('idx_market_data_ticker_date', 'market_data', ['ticker', 'date'], unique=False)
    op.create_table('portfolio_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('cash_balance', sa.Float(), nullable=True),
    sa.Column('equity_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_history_user_date', 'portfolio_history', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_portfolio_history_id'), 'portfolio_history', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_history_user_id'), 'portfolio_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_history_user_id'), table_name='portfolio_history')
    op.drop_index(op.f('ix_portfolio_history_id'), table_name='portfolio_history')
    op.drop_index('idx_portfolio_history_user_date', table_name='portfolio_history')
    op.drop_table('portfolio_history')
    op.drop_index('idx_market_data_ticker_date', table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
